### ISSUE TITLE
Installing requirements.txt

### ISSUE THREAD

**Issue by bhavini-jeloka** [SAGNIKMJR/move2hear-active-AV-separation#2]
Hello!
I have tried installing requirements.txt but it gives an error because of the presence of local files (for instance, aiohttp @ file:///tmp/build/80754af9/aiohttp_1614360990960/work). Can you please let me know how to work around it? Thank you in advance.

**Comment by SAGNIKMJR** [comment]
Hi,

Thanks for reaching out!

I have updated the requirements.txt file. Hope that helps.

Sagnik
